### ISSUE TITLE
How much should the tables in quick search and detail search share state?

### ISSUE THREAD

**Issue by Erikdzo** [geocollections/EMA#193]
Right now the tables in quick and detail search shares table options (current page, sorting, pagination size). For example changing pages in drillcore quick search also changes pages in detail search. 

Should those states be separate or shared?

Also should these tables all have separate states for items? Right now the items are shared between corresponding quick and detail search tables, but when switching between those the items are refreshed to not show incorrect results.

To me it seems that sharing the state may result in problems down the line, like dealing with resetting sorting or page when necessary, and giving each table its own state (probably in not in store but in the component/page data) could make code more easily debuggable and understandable.

**Comment by enmust** [comment]
Quick search and detail search states probably shouldn't share any search data and should be separated. 

About the detail search states I believe it would make sense to have a state per detail search. This will probably mean that we have to work with some duplicate boilerplate code but at least this keeps the data strongly separated and code more readable.

FYI: In edit app we are somewhat sharing the search state across all detail search views which works OK but it just makes harder to implement custom functionality per search etc. Nuxt.js also favours creating separate states because it removes some boilerplate code

A few views probably will have the option to search using map / facets / maybe some new way (analyses) which makes sense to have a separate state per detail search.
