### ISSUE TITLE
Quick search with operators

### ISSUE THREAD

**Issue by ollehints** [geocollections/EMA#201]
The quick search should accept + and - operators as conventional solr q search. 
Currently search by multiple keywords provides incorrect results. For instance, search by **+käesla +702** should provide only one locality. solr query: q=%2Bkäesla%20%2B702
This may be problem on API side too, but in geokirjandus the operators work as expected.

**Comment by enmust** [comment]
Hmm, isn't this actually the correct response because when using both query parts separately **+käesla** returns 6 results and **+702** returns 2 results (one is already returned in +käesla results) then the combined results is 7. According to the [docs](https://solr.apache.org/guide/6_6/the-standard-query-parser.html) it seems that empty space acts as OR and that's why 7 localities are returned. For example only 1 locality would be returned if query string is **+käesla AND +702** or wrapped in quotation marks **"+käesla +702"**

**Comment by enmust** [comment]
Yes, this seems weird. Currently the empty space seems to act as a OR operator. For example using **+käesla AND +702** string would return correct results.
